package com.sekapato.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "girl")
public class Girl {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long id;

    // The user's name

    public String realName;

    public String realKana;

    public String name;

    public String kana;

    public Integer realAge;

    public Integer age;

    public String address;

    public String tel;

    public String lineId;

    public String email;

    public Boolean identificationFlg;

    public Integer height;

    public String cup;

    public Integer waist;

    public Integer hip;

    public Integer type;

    public Integer userClass;

    public String occupation;



    public String bloodType;

    public String language;

    public Boolean golfFlg;

    public String hobby;

    public String charmPoint;

    public Boolean smokingFlg;

    public Boolean alcholeFlg;

    public String aboutOffer;

    public String comment;

    public String url;

    public Boolean deleteFlg;
    
    public Girl(){
        
    }
    public Girl(long id, String realName, String realKana, String name, String kana, Integer realAge, Integer age,
            String address, String tel, String lineId, String email, Boolean identificationFlg, Integer height,
            String cup, Integer waist, Integer hip, Integer type, Integer userClass, String occupation,
            String constellation, String bloodType, String langauge, Boolean golfFlg, String hobby, String charmPoint,
            Boolean smokingFlg, Boolean akcholeFlg, String aboutOffer, String comment, String url) {
        super();
        this.id = id;
        this.realName = realName;
        this.realKana = realKana;
        this.name = name;
        this.kana = kana;
        this.realAge = realAge;
        this.age = age;
        this.address = address;
        this.tel = tel;
        this.lineId = lineId;
        this.email = email;
        this.identificationFlg = identificationFlg;
        this.height = height;
        this.cup = cup;
        this.waist = waist;
        this.hip = hip;
        this.type = type;
        this.userClass = userClass;
        this.occupation = occupation;
        this.bloodType = bloodType;
        this.language = langauge;
        this.golfFlg = golfFlg;
        this.hobby = hobby;
        this.charmPoint = charmPoint;
        this.smokingFlg = smokingFlg;
        this.alcholeFlg = akcholeFlg;
        this.aboutOffer = aboutOffer;
        this.comment = comment;
        this.url = url;
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getRealName() {
        return realName;
    }
    public void setRealName(String realName) {
        this.realName = realName;
    }
    public String getRealKana() {
        return realKana;
    }
    public void setRealKana(String realKana) {
        this.realKana = realKana;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getKana() {
        return kana;
    }
    public void setKana(String kana) {
        this.kana = kana;
    }
    public Integer getRealAge() {
        return realAge;
    }
    public void setRealAge(Integer realAge) {
        this.realAge = realAge;
    }
    public Integer getAge() {
        return age;
    }
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getAddress() {
        return address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTel() {
        return tel;
    }
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getLineId() {
        return lineId;
    }
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getIdentificationFlg() {
        return identificationFlg;
    }
    public void setIdentificationFlg(Boolean identificationFlg) {
        this.identificationFlg = identificationFlg;
    }
    public Integer getHeight() {
        return height;
    }
    public void setHeight(Integer height) {
        this.height = height;
    }
    public String getCup() {
        return cup;
    }
    public void setCup(String cup) {
        this.cup = cup;
    }
    public Integer getWaist() {
        return waist;
    }
    public void setWaist(Integer waist) {
        this.waist = waist;
    }
    public Integer getHip() {
        return hip;
    }
    public void setHip(Integer hip) {
        this.hip = hip;
    }
    public Integer getType() {
        return type;
    }
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getUserClass() {
        return userClass;
    }
    public void setUserClass(Integer userClass) {
        this.userClass = userClass;
    }
    public String getOccupation() {
        return occupation;
    }
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getBloodType() {
        return bloodType;
    }
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }
    public String getLanguage() {
        return language;
    }
    public void setLangauge(String language) {
        this.language = language;
    }
    public Boolean getGolfFlg() {
        return golfFlg;
    }
    public void setGolfFlg(Boolean golfFlg) {
        this.golfFlg = golfFlg;
    }
    public String getHobby() {
        return hobby;
    }
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }
    public String getCharmPoint() {
        return charmPoint;
    }
    public void setCharmPoint(String charmPoint) {
        this.charmPoint = charmPoint;
    }
    public Boolean getSmokingFlg() {
        return smokingFlg;
    }
    public void setSmokingFlg(Boolean smokingFlg) {
        this.smokingFlg = smokingFlg;
    }
    public Boolean getAkcholeFlg() {
        return alcholeFlg;
    }
    public void setAkcholeFlg(Boolean akcholeFlg) {
        this.alcholeFlg = akcholeFlg;
    }
    public String getAboutOffer() {
        return aboutOffer;
    }
    public void setAboutOffer(String aboutOffer) {
        this.aboutOffer = aboutOffer;
    }
    public String getComment() {
        return comment;
    }
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }
    @Override
    public String toString() {
        return "Girl [id=" + id + ", realName=" + realName + ", realKana=" + realKana + ", name=" + name + ", kana="
                + kana + ", realAge=" + realAge + ", age=" + age + ", address=" + address + ", tel=" + tel + ", lineId="
                + lineId + ", email=" + email + ", identificationFlg=" + identificationFlg + ", height=" + height
                + ", cup=" + cup + ", waist=" + waist + ", hip=" + hip + ", type=" + type + ", userClass=" + userClass
                + ", occupation=" + occupation + ", constellation="  + ", bloodType=" + bloodType
                + ", langauge=" + language + ", golfFlg=" + golfFlg + ", hobby=" + hobby + ", charmPoint=" + charmPoint
                + ", smokingFlg=" + smokingFlg + ", akcholeFlg=" + alcholeFlg + ", aboutOffer=" + aboutOffer
                + ", comment=" + comment + ", url=" + url + "]";
    }

    

}
